name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.6
      uses: actions/setup-node@v1
      with:
        node-version: "14.6.0"
    - name: Install Dependencies
      run: npm ci
    - name: Export Resume
      run: npm export.js
    - name: Deploy to S3
      uses: jsjohnstone/s3-site-deploy@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2' 
        SOURCE_DIR: 'export/.'
    
